### ISSUE TITLE
Nuxt, VuePress, NuxtPress, why?

### ISSUE THREAD

**Issue by Chris2011** [nuxt/press#71]
So in the last couple of days I wanted to have a look into Nuxt. Happily, I found VuePress which is based on Nuxt (?). Now we have NuxtPress. But why? What are the differences? Why not using VuePress? It is not a critic, just a question, because I can't understand it.

**Comment by pimlie** [comment]
Hey, not sure why you thought this but VuePress is not using Nuxt, its a pure/vanilla Vue implementation.

NuxtPress is a module for Nuxt to create VuePress-like-functionality just as easy as with VuePress, but with a lot more options due to it being able to be integrated within a Nuxt project. Hope this clears somethings up :)

**Comment by Chris2011** [comment]
Ok, it was inspired by nuxt, so maybe I missunderstood it :). Sry and thx for the explanation.
